name: Deploy to WordPress.org SVN
on:
  push:
    tags:
      - "*" # Se activa cada vez que creas un tag (ej: v1.0.1)
  workflow_dispatch: # This enables the manual button

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: WordPress.org Deploy
        uses: 10up/action-wordpress-dot-org-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: dfx-parish-retreat-letters
